version: "3.6"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: peterv748/fractal_demo
    deploy:
      replicas: 5
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
	  update_config:
	      parallelism: 2
		  delay: 1s
		  momitor: 1s
		  order: stop-first
    ports:
      - "4000:80"
    networks:
      - webnet
	env_file:
	  - setenv.env

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "d:/peter/Documents/python code/dev/test_web/data"
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - webnet
networks:
  webnet: